### ISSUE TITLE
Can't use with Bash

### ISSUE THREAD

**Issue by LIJI32** [hbang/NewTerm#103]
Upon setting the default shell from `zsh` to `bash` (`chsh -s bash`), NewTerm3 gets a "Session Ended" line upon start up.

**Comment by iAdam1n** [comment]
You could try installing gettext-localizations and if that does not work reinstall system-cmds.

**Comment by LIJI32** [comment]
Neither seemed to do it, but upon doing the first I got an error about `/var/jb/bin/bash` missing (it exists, it symlinks to `/var/jb/usr/bin/bash` which also exists), and upon doing the second I got an error about `/var/jb/bin/bash-bash` missing. Thanks for the quick reply!

**Comment by LIJI32** [comment]
Not sure why it only affected NewTerm but not SSH, but `_rl_init_locale` from readline makes `bash` crash when launched from NewTerm. I "fixed" it by patching `_rl_init_locale` in readline to be a nop.
