### ISSUE TITLE
Crash On iPhone 4S, IOS 7.1.2

### ISSUE THREAD

**Issue by YtnbFirewings** [hbang/NewTerm#27]
Crash on my 4S when change orientation，I check the crash report and find value of dirty is NULL and setDirty try to access it.

After Add Check Code, Everything seems right.
```
- (void)resetDirty {
           if (dirty != NULL)
           {
		memset(dirty,0,WIDTH *HEIGHT *sizeof(char));
           }
}

- (void)setDirty {
           if (dirty != NULL)
           {
		memset(dirty, 1, WIDTH *HEIGHT *sizeof(char));
           }
	   [refreshDelegate refresh];
}
```

**Comment by kirb** [comment]
Fixed in e63e61e; thanks. Still doesn't entirely fix terminal size reporting though.
