### ISSUE TITLE
Copy & Paste are useful features

### ISSUE THREAD

**Issue by matt-matt1** [hbang/NewTerm#28]
Often I use the terminal to display some information to copy and then paste into another application, and v.v.. For example, I might copy a bit of text from a webpage and paste it into a file.
Matt

**Comment by kirb** [comment]
Already fixed by the rewrite (which has had development stalled for some time now due to lack of interest).

**Comment by matt-matt1** [comment]
So how can I install that version?

**Comment by kousu** [comment]
Yes, please! It's not in AppCake's Cydia repo. Is there a .deb of it around? I don't have easy access tp OS X, only iOS, so if I need OS X to build this I am out of luck.

I take it that the rewrite happened after [the most recent release](https://github.com/hbang/NewTerm/releases/tag/1.0b1)?

**Comment by kirb** [comment]
NewTerm is built using [Theos](https://github.com/kirb/theos/wiki), which supports OS X, iOS, Windows, and Linux. (If you need assistance, visit [IRC](http://iphonedevwiki.net/index.php/IRC) – this isn’t really the place for that.) Do note that the current state of the rewritten version has even less features than 1.0b1, hence why it isn’t released yet.
