### ISSUE TITLE
How to get latest?

### ISSUE THREAD

**Issue by matt-matt1** [hbang/NewTerm#29]
I have version 1 beta, how can I upgrade or install latest where fixes have been made?

**Comment by matt-matt1** [comment]
Thanx

**Comment by kirb** [comment]
There is no compiled build available other than beta 1. You will need to build it yourself from this repository.

You need Theos; see http://iphonedevwiki.net/index.php/Theos. Then you can run `make package install`.

Given this hasn't been released, there's no guarantee that it works. I recall there are some bugs that aren't yet addressed.
