### ISSUE TITLE
"Module is unknown. Press any key to restart" on ipod touch 6g ios 9.0.2 Pangu Jailbreak

### ISSUE THREAD

**Issue by agreg0ire** [hbang/NewTerm#30]
Below the entire error message that yields nothing on google:

login: pam error (line 400) : module is unknown [process completed] press any key to restart.

And when i press any key it outputs the same error message...

**Comment by kirb** [comment]
This is an issue with the PAM package in Telesphoreo. Unfortunately it hasn't been fixed yet. As far as I know, this occurs on 64-bit devices, regardless of which terminal app you use.

**Comment by agreg0ire** [comment]
First thanks for swift reply sir.
Yes ipod 6gen is 64 bits arch.

Any idea to advise me because none of:

MTerminal, mobileterminal, ios terminal and whiteTerminal will work

:(

**Comment by kirb** [comment]
Not really any solution yet, just have to wait. It's the early days of the iOS 9 jailbreak; give it a few weeks and everything will be working again.

**Comment by agreg0ire** [comment]
Yes it will show up in several weeks somwhere on internet.
I don't close the issue.
Thanks again

**Comment by iAdam1n** [comment]
PAM Module received an update a couple of hours ago which fixed this issue.
