### ISSUE TITLE
Unable to view settings

### ISSUE THREAD

**Issue by ZeldaZach** [hbang/NewTerm#34]
iPhoneX running 11.3.1 with NewTerm2 2.0

Hey hbang, I’ve been using your terminal for a bit, and it’s a great tool, but I can’t seem to access the in app settings. 

My initial thought was to go to settings app, but nothing there. Looking through the source tree, seems to be an in app settings option, but I couldn’t trigger it on my device. 

I went to [reddit](https://amp-reddit-com.cdn.ampproject.org/v/s/amp.reddit.com/r/jailbreak/comments/89c22q/question_why_the_newterm_2_settings_are_hidden/?amp_js_v=0.1&usqp=mq331AQGCAEoATgA) and they provided tips, but they didn’t seem to work. 

Is there a better workaround and/or a planned fix?

**Comment by kirb** [comment]
I [wrote](https://www.reddit.com/r/jailbreak/comments/89c22q/question_why_the_newterm_2_settings_are_hidden/dwrlf2x/) on the linked Reddit thread:

>It’s in the app but hard to find, sorry. Swipe down on the terminal screen and you’ll find the settings button in the bottom-left. (You might need to fill up the screen before it’ll let you scroll. Again yeah, not the best placement, it’ll be moved in an update.)
