### ISSUE TITLE
Arrow Keys on Wireless Keyboard

### ISSUE THREAD

**Issue by SmiVan** [hbang/NewTerm#35]
Using arrows on a bluetooth keyboard doesn't work.
Tested with Apple's magic keyboard and iPad (iOS 9.3.3) on NewTerm 2.1.
Not a problem of the keyboard as I tested that it works in Notes.

This was discussed in #16, but the wireless part doesn't seem to work, so I'm bringing this up again.

**Comment by kirb** [comment]
I misread that issue when I closed it, that was about hardware arrow keys not software arrow keys 😕

Luckily, this was recently implemented in 0136c2a (not released yet) as part of my effort to get NewTerm working on macOS. I’ll leave this issue open till it’s been merged into master.

**Comment by JingMAmax** [comment]
That would be great ! and make this terminal much more convenient as I'm using iPad Pro with Smart Keyboard. 
best wishes~

**Comment by kirb** [comment]
2.2 is out with arrow key support and meta (esc) key support. No ctrl key support yet.
