### ISSUE TITLE
[Enhancement] Copy/Paste/Home/End?

### ISSUE THREAD

**Issue by TheAwesome98-Real** [hbang/NewTerm#44]
I don’t want to keep turning on Voice Control to paste, and also I forgot to type git clone and had to press `<` a lot of times to get to the end

**Comment by kirb** [comment]
This seems like a duplicate of #39 for the first part. For the second part, tap Fn to reveal Home/End keys.

You may also find it useful to be aware of the [emacs-style shortcuts](https://superuser.com/questions/352983/which-emacs-shortcuts-are-useful-in-bash) most programs (including bash, zsh, and nano) support, which includes `Ctrl-A` and `Ctrl-E` as Home and End equivalents.

**Comment by TheAwesome98-Real** [comment]
Oh, thanks!

**Comment by TheAwesome98-Real** [comment]
Yep that fully solved my issue, 3 finger tap revealed the copy&paste menu. Thanks again!
