### ISSUE TITLE
Press and hold on + button always creates new tab [macOS]

### ISSUE THREAD

**Issue by quiprr** [hbang/NewTerm#54]
On the Mac app, when the + is pressed and held, a popup will come up asking for new window or close window.

1.) Window should be replaced with Tab/Instance
2.) If close is pressed, it shouldn't create a new tab
3.) It shouldn't be moving the window

**Comment by kirb** [comment]
Mac-native tabs were implemented in a later build, pretty much fixes this ticket. App wasn’t really doing anything to accommodate macOS window system before that.
