### ISSUE TITLE
Sudo password

### ISSUE THREAD

**Issue by Gnomsky** [hbang/NewTerm#77]
Hello. i have an iPad mini 2, running ios 12.5.5, jailbroken with chimera.

Then i try update my packages (-apt update), i give an error:

E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)

But i try -sudo apt update, but i don't know my sudo password. There i can find it?

**Comment by kirb** [comment]
The default password is alpine.

Sorry, this isn’t the right place for general terminal help. I’d suggest posting on [/r/jailbreak](https://www.reddit.com/r/jailbreak), or [discord](https://discord.gg/jb).

**Comment by Gnomsky** [comment]
Ty!
