### ISSUE TITLE
Issues fugu15 max

### ISSUE THREAD

**Issue by Efrayyy** [hbang/NewTerm#92]
![61C1112C-DBDA-4D6B-8DF4-E088070D20E9](https://user-images.githubusercontent.com/129629797/229323924-56c9d35c-f238-44d5-8756-653abd0ead85.png)
When open newterm 3 beta 
Writing season ended 
Can you fixed .. thank you

**Comment by iAdam1n** [comment]
We're aware but aren't sure yet if it's an issue on our side because on palera1n rootless it works fine when you install updates but not on Fugu15. Been talking to opa334 and Nick Chan regarding this issue but yet to have a solution.

**Comment by iAdam1n** [comment]
It's actually already solved now.
